services:
  library-maintenance-api:
    build: 
      context: .
      dockerfile: library-maintenance-api/Dockerfile
    ports:
      - 5001:5001
    env_file:
      - .env

  library-maintenance-ui:
    build: 
      context: .
      dockerfile: library-maintenance-ui/Dockerfile
    ports:
      - 80:80
    env_file:
      - .env